### ISSUE TITLE
template names not being generated

### ISSUE THREAD

**Issue by gb96** [AdamBrodzinski/meteor-generate#10]
When I generated posts page, ran meteor, then visited it in my browser I got the following error:
```
Couldn't find a template named "posts" or "posts". Are you sure you defined it?
```

Looking inside the generated files the problem is obvious, e.g. /client/pages/posts/index.html:

```html
<template name='compName'>

<div class='comp-name'>
  <h1>Page: compName</h1>
  <p>Find me in client/pages/compName/index.html</p>
</div>

</template>
```

The index.html was generated from the version of meteor-generate I installed last week.  I will try updating to the most recent version and regenerate everything and see if the error is still there.

**Comment by gb96** [comment]
Deleted and regenerated, and template names were okay.  So not sure what happened originally, but in any case consider it fixed :)

**Comment by AdamBrodzinski** [comment]
Oh weird! The pages module is pretty clunky... once the rest of the features get implemented I need to swing back and refactor it to use the new parsing/transforming modules! From the error above it almost seems like it copied over the templates but did not run the rest of the code to replace the variable names.
