### ISSUE TITLE
mgen create <name> hangs

### ISSUE THREAD

**Issue by wizonesolutions** [AdamBrodzinski/meteor-generate#6]
`npm install -g meteor-generate coffee-script`

`mgen create example`

`Creating basic app structure`

just hangs forever there.

Did I do something wrong? How long should it take?

**Comment by Morganjackson** [comment]
I just tested it for you and it finished in under 3 seconds.

→ mgen create exmaple

Creating basic app structure
    Created: both/routes.js
    Created: .jshintrc
    Created: .jshintignore
    Created: makefile
    Removed: original boilerplate
Updating Packages
    Removed Package: insecure
    Removed Package: autopublish
    Added Package: iron:router

-------------------------------------------
  type cd exmaple to navigate to project
  then the meteor command to start a server
-------------------------------------------

**Comment by wizonesolutions** [comment]
I'm not sure why it didn't work for me, then. However, the rest of the tool works if I manually copy in the initial structure as @AdamBrodzinski recommended on Twitter. I guess I will close this.

**Comment by AdamBrodzinski** [comment]
@wizonesolutions does it still hang if you create a new test app?

**Comment by wizonesolutions** [comment]
For some strange reason, not anymore. I don't even see any commits to the
code base. What magic did you do!?

**Comment by AdamBrodzinski** [comment]
Hmm, not sure I follow exactly. You're not seeing your own commits or you're not seeing the ones for a git checkout version of meteor-generate?

Basically what's happening is it calls the `meteor create foo` command from the command line and then removes some default packages, moves a default folder/files in, and prints out the progress.

https://github.com/AdamBrodzinski/meteor-generate/blob/master/lib/init.js#L48

```javascript
  // Private: Run a command on the command line.
  //
  // command - the {String} command to run
  // callback - a {Function} to call when complete
  //
  _runTerminalCommand: function(command, callback) {
    var exec = require('child_process').exec;

    exec(command, function (err) {
      if (err) puts('exec error: ' + err);
      callback.call(this);
    });
  },
```

**Comment by wizonesolutions** [comment]
I meant that the problem away even though I didn't see any code changes to
the meteor-generate project. I was just curious why.

**Comment by AdamBrodzinski** [comment]
@wizonesolutions ah, I think it was just an issue on your system... no code was changed. I've heard of some issues with the Meteor constraint solver taking 5+mins to complete so perhaps it was an issue getting the dependencies downloaded and satisfied. Currently I don't think any of the Meteor std out is printing... perhaps i'll look into printing that out in case it's taking a while.
